[package]
name = "day_17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
priority-queue = "1.3.2"

[features]
debug_output = []
